# Generated by Django 4.2.2 on 2023-07-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_name',
            new_name='name',
        ),
    ]
