# Generated by Django 4.2.2 on 2023-07-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_name_tasks_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
