# Generated by Django 4.2.2 on 2023-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-07-20'),
            preserve_default=False,
        ),
    ]
